Services - Work Opportunities:
  summary: Services - Work Opportunities
  description: >-
   Job Hub is acting as provider platform(BPP) which hosts the jobs and Worker Hub is acting as seeker platform(BAP) which helps the workers to find jobs.
  example_set:
    $ref: "./Services_Work_Opportunities_yaml/index.yaml"